version: '3.7'

services:
    mysql:  
      build:
        context: mysql
      image: mysqlimg
      container_name: baza
      environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      ports:
      - "33061:3306"
      volumes:
      - ./db-data:/var/lib/mysql

    api:  
      build: helloworld
      image: hwapi
      container_name : api
      ports:
        - "8080:8080"
      depends_on:
       - mysql
      volumes:
       - ./app-logs:/logs
       - ./app-logs/archived:/archived
   
    app:  
      build: vue
      image: vueapp  
      container_name : vueApp
      ports:
      - "4000:4000"
      depends_on:
       - api
